"""baseline: existing schema

Revision ID: adbe2ff4f187
Revises: 
Create Date: 2026-10-08 23:30:29.974517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'adbe2ff4f187'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_session_states',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('state_json', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('buyer_preferences',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('statement', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'kind', 'statement', name='uq_pref_buyer_kind_statement')
    )
    op.create_index(op.f('ix_buyer_preferences_buyer_id'), 'buyer_preferences', ['buyer_id'], unique=False)
    op.create_table('context_checkpoints',
    sa.Column('checkpoint_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_context_checkpoints_session_id'), 'context_checkpoints', ['session_id'], unique=False)
    op.create_table('context_operations',
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('expected_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('deadline', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_index(op.f('ix_context_operations_session_id'), 'context_operations', ['session_id'], unique=False)
    op.create_table('conversation_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_events_session_id'), 'conversation_events', ['session_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index('ix_msg_session_turn', 'conversation_messages', ['session_id', 'turn_index'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_conversation_sessions_buyer_id'), 'conversation_sessions', ['buyer_id'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_amount_minor', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('shipping_address_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_buyer_id'), 'orders', ['buyer_id'], unique=False)
    op.create_table('session_write_claims',
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('fence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('task_access_bindings',
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=256), nullable=False),
    sa.Column('buyer_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('trade_confirmations',
    sa.Column('confirmation_id', sa.String(length=32), nullable=False),
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('buyer_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('resolved_at', sa.String(length=40), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_trade_decision'),
    sa.PrimaryKeyConstraint('confirmation_id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_index('ix_trade_confirmation_owner', 'trade_confirmations', ['buyer_id', 'session_id', 'created_at'], unique=False)
    op.create_table('trade_operations',
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('confirmation_id', sa.String(length=32), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('operation_id'),
    sa.UniqueConstraint('confirmation_id')
    )
    op.create_table('trade_sku_inventory',
    sa.Column('sku_id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('stock', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.CheckConstraint('stock >= 0', name='ck_trade_stock_nonnegative'),
    sa.CheckConstraint('unit_price_minor >= 0', name='ck_trade_price_nonnegative'),
    sa.PrimaryKeyConstraint('sku_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('sku_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('unit_price_minor', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_table('trade_sku_inventory')
    op.drop_table('trade_operations')
    op.drop_index('ix_trade_confirmation_owner', table_name='trade_confirmations')
    op.drop_table('trade_confirmations')
    op.drop_table('task_access_bindings')
    op.drop_table('session_write_claims')
    op.drop_index(op.f('ix_orders_buyer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_conversation_sessions_buyer_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('ix_msg_session_turn', table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversation_events_session_id'), table_name='conversation_events')
    op.drop_table('conversation_events')
    op.drop_index(op.f('ix_context_operations_session_id'), table_name='context_operations')
    op.drop_table('context_operations')
    op.drop_index(op.f('ix_context_checkpoints_session_id'), table_name='context_checkpoints')
    op.drop_table('context_checkpoints')
    op.drop_index(op.f('ix_buyer_preferences_buyer_id'), table_name='buyer_preferences')
    op.drop_table('buyer_preferences')
    op.drop_table('agent_session_states')
    # ### end Alembic commands ###
